additional wrappers around AmazonDrive API endpoints needed for moving files
ncw/go-acd pull request #2
Opened 2016-11-04 16:51 UTC by breunigs

2016-11-05 11:22 UTC, ncw requested changes
Thanks for the patch - the extra methods look very useful!

I've put a few comments inline.

Can you fixup, squash and rebase onto master please?

In particular please don't send merge commits in pull requests as it makes reviewing them a lot harder and in general isn't necessary!

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +func (n *Node) UpdateMetadata(name *string, description *string) (*http.Response, error) {
Can you return the Node that Amazon Drive returns please?  My policy is always to return stuff it if comes back in the API.  The caller can always ignore it...

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +// Updates metadata fields name or description of Node n. If a given field is nil,
Go comments for external function should be in the style `// FuncName ...` so this should be `// UpdateMetadata changes name or ...`

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

Though I see you removed this in the next changeset ;-)

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +func (n *Node) Restore() (*http.Response, error) {
This also returns a Node which we should return to the user.

Needs a comment as it is an externally visible function.

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +func (n *Node) RemoveParent(parentId string) (*http.Response, error) {
Needs a comment as it is an externally visible function.

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +func (n *Node) AddParent(newParentId string) (*http.Response, error) {
Needs a comment as it is an externally visible function.

2016-11-05 11:22 UTC, ncw commented on nodes.go
> +func (n *Node) ReplaceParent(oldParentId string, newParentId string) (*http.Response, error) {
I've checked the implementation - looks good!

Needs a comment as it is an externally visible function.

2016-11-05 11:22 UTC, ncw commented on nodes.go
> -func (n *Node) Rename(newName string) (*Node, *http.Response, error) {
I'd prefer to return the Node that Amazon Drive returns - so I don't think we need to change this, unless you know something I don't?

2016-11-05 13:12 UTC, breunigs commented
I think I have fixed all of your input.

2016-11-06 14:23 UTC, ncw commented
Super job thanks! I've merged that.

2016-11-06 14:24 UTC, merged